// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using NorthWithConfiguration.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using NorthWithConfiguration.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace NorthWithConfiguration.Contexts
{
    public class PhoneTypeConfiguration : IEntityTypeConfiguration<PhoneType>
    {
        public void Configure(EntityTypeBuilder<PhoneType> entity)
        {
            entity.HasKey(e => e.PhoneTypeIdenitfier);
        }
    }
}
