// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using NorthWindCore.Interfaces;
using NorthWindCore.Models;

namespace North.Models
{
    public partial class Categories : IModelBaseEntity
    {
        public Categories()
        {
            Products = new HashSet<Products>();
        }

        public int Id => CategoryID;
        /// <summary>
        /// Primary key
        /// </summary>
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public byte[] Picture { get; set; }

        public virtual ICollection<Products> Products { get; set; }

        public override string ToString() => CategoryName;

    }
}