// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using TimeLibraryCore.Models;

namespace TimeLibraryCore.Context
{
    public class EventsConfiguration : IEntityTypeConfiguration<Events>
    {
        public void Configure(EntityTypeBuilder<Events> entity)
        {
            entity.HasKey(e => e.EventId)
                .HasName("PK__Events__7944C87058D762E2");
        }
    }
}
