// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthWithFoldersAnnotations.Models
{
    [Table("BusinessEntityPhone")]
    public partial class BusinessEntityPhone
    {
        [Key]
        [Column("BusinessEntityPhoneID")]
        public int BusinessEntityPhoneId { get; set; }
        public string PhoneNumber { get; set; }
        [Column("PhoneNumberTypeID")]
        public int? PhoneNumberTypeId { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}