// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthWithFoldersAnnotations.Models
{
    public partial class Contact
    {
        public Contact()
        {
            ContactDevices = new HashSet<ContactDevice>();
            Customers = new HashSet<Customer>();
        }

        [Key]
        public int ContactId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int? ContactTypeIdentifier { get; set; }

        [ForeignKey(nameof(ContactTypeIdentifier))]
        [InverseProperty(nameof(ContactType.Contacts))]
        public virtual ContactType ContactTypeIdentifierNavigation { get; set; }
        [InverseProperty(nameof(ContactDevice.Contact))]
        public virtual ICollection<ContactDevice> ContactDevices { get; set; }
        [InverseProperty(nameof(Customer.Contact))]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}