// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthWithFoldersAnnotations.Models
{
    public partial class ContactDevice
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        public int? ContactId { get; set; }
        public int? PhoneTypeIdentifier { get; set; }
        public string PhoneNumber { get; set; }

        [ForeignKey(nameof(ContactId))]
        [InverseProperty("ContactDevices")]
        public virtual Contact Contact { get; set; }
        [ForeignKey(nameof(PhoneTypeIdentifier))]
        [InverseProperty(nameof(PhoneType.ContactDevices))]
        public virtual PhoneType PhoneTypeIdentifierNavigation { get; set; }
    }
}