// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthWithFoldersAnnotations.Models
{
    [Table("ContactType")]
    public partial class ContactType
    {
        public ContactType()
        {
            Contacts = new HashSet<Contact>();
            Customers = new HashSet<Customer>();
            Employees = new HashSet<Employee>();
        }

        [Key]
        public int ContactTypeIdentifier { get; set; }
        public string ContactTitle { get; set; }

        [InverseProperty(nameof(Contact.ContactTypeIdentifierNavigation))]
        public virtual ICollection<Contact> Contacts { get; set; }
        [InverseProperty(nameof(Customer.ContactTypeIdentifierNavigation))]
        public virtual ICollection<Customer> Customers { get; set; }
        [InverseProperty(nameof(Employee.ContactTypeIdentifierNavigation))]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}