// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthWithFoldersAnnotations.Models
{
    public partial class Country
    {
        public Country()
        {
            Customers = new HashSet<Customer>();
            Employees = new HashSet<Employee>();
            Suppliers = new HashSet<Supplier>();
        }

        [Key]
        public int CountryIdentifier { get; set; }
        public string Name { get; set; }

        [InverseProperty(nameof(Customer.CountryIdentifierNavigation))]
        public virtual ICollection<Customer> Customers { get; set; }
        [InverseProperty(nameof(Employee.CountryIdentifierNavigation))]
        public virtual ICollection<Employee> Employees { get; set; }
        [InverseProperty(nameof(Supplier.CountryIdentifierNavigation))]
        public virtual ICollection<Supplier> Suppliers { get; set; }
    }
}