// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TimeLibraryCore.Models
{
    public partial class Movies
    {
        [Key]
        public int Id { get; set; }
        public TimeSpan? Duration { get; set; }
        public string Title { get; set; }
    }
}