// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NorthOlderModel.Models
{
    public partial class Customers
    {
        [Key]
        [Display(Name = "Id")]
        public int CustomerIdentifier { get; set; }
        [Required]
        [StringLength(40)]
        [Display(Name = "Company")]
        public string CompanyName { get; set; }
        [StringLength(30)]
        [Display(Name = "Contact")]
        public string ContactName { get; set; }
        [StringLength(60)]
        [Display(Name = "Street")]
        public string Address { get; set; }

        [StringLength(15)]
        [Display(Name = "City")]
        public string City { get; set; }
        [StringLength(15)]
        [Display(Name = "Region")]
        public string Region { get; set; }
        [StringLength(10)]
        [Display(Name = "Postal")]
        public string PostalCode { get; set; }
        [StringLength(15)]
        [Display(Name = "Country")]
        public string Country { get; set; }
        [StringLength(24)]
        [Display(Name = "Phone")]
        public string Phone { get; set; }
        [StringLength(24)]
        [Display(Name = "FAX")]
        public string Fax { get; set; }
        [Display(Name = "Contact Type Id")]
        public int? ContactTypeIdentifier { get; set; }

        [ForeignKey(nameof(ContactTypeIdentifier))]
        [InverseProperty(nameof(ContactType.Customers))]
        public virtual ContactType ContactTypeIdentifierNavigation { get; set; }
    }
}